import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
import type { IReport } from '../../models/Report';

export async function generateReportPdf(report: IReport): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);

  let page = doc.addPage([595, 842]);
  const { width, height } = page.getSize();
  let y = height - 50;

  const drawText = (text: string, size: number, bold = false, color = rgb(0.1, 0.1, 0.2)) => {
    if (y < 60) {
      page = doc.addPage([595, 842]);
      y = height - 50;
    }
    page.drawText(text, { x: 50, y, size, font: bold ? fontBold : font, color });
    y -= size + 8;
  };

  drawText('PulseIQ Intelligence Report', 22, true, rgb(0.36, 0.42, 1));
  y -= 10;
  drawText(`URL: ${report.url}`, 11);
  drawText(`Scan Date: ${report.createdAt.toLocaleString()}`, 11);
  if (report.scanDuration) {
    drawText(`Duration: ${(report.scanDuration / 1000).toFixed(1)}s`, 11);
  }

  y -= 15;
  drawText('Scores', 16, true);
  const scoreEntries = Object.entries(report.scores);
  for (const [key, value] of scoreEntries) {
    drawText(`${key.charAt(0).toUpperCase() + key.slice(1)}: ${value}/100`, 12);
  }

  y -= 15;
  drawText('Performance Metrics', 16, true);
  for (const [key, value] of Object.entries(report.performance.metrics)) {
    drawText(`${key}: ${value}`, 10);
  }

  y -= 10;
  drawText('Performance Recommendations', 14, true);
  for (const rec of report.performance.recommendations.slice(0, 6)) {
    drawText(`• ${rec}`, 10);
  }

  y -= 10;
  drawText('SEO Recommendations', 14, true);
  for (const rec of report.seo.recommendations.slice(0, 6)) {
    drawText(`• ${rec}`, 10);
  }

  y -= 10;
  drawText('Security Recommendations', 14, true);
  for (const rec of report.security.recommendations.slice(0, 6)) {
    drawText(`• ${rec}`, 10);
  }

  y -= 10;
  drawText('Technologies Detected', 14, true);
  for (const tech of report.technologies.slice(0, 12)) {
    drawText(`• ${tech.name} (${tech.category}) — ${tech.confidence}%`, 10);
  }

  page.drawText('Generated by PulseIQ — See Everything Your Website Is Hiding', {
    x: 50,
    y: 30,
    size: 8,
    font,
    color: rgb(0.5, 0.5, 0.6),
  });

  return doc.save();
}
